dashboard files added
Buzxxx/ehe_next pull request #9
Opened 2024-05-09 16:48 UTC by grvx-github

2024-05-10 19:24 UTC, Buzxxx requested changes
Hello grvx,

We need to address these changes before merging it in Prod.
Please setup a call tomorrow, lets have a discussion.

Thank you,
Avinash

2024-05-10 19:24 UTC, Buzxxx commented on .All.swp
This file type should not be pushed

2024-05-10 19:24 UTC, Buzxxx commented on .More.swp
This file type should not be pushed

2024-05-10 19:24 UTC, Buzxxx commented on components.json
project property update should not come with feature updates, but still its okay

2024-05-10 19:24 UTC, Buzxxx commented on package-lock.json
do we need MUI icons? or can we use heroicons?

2024-05-10 19:24 UTC, Buzxxx commented on src/components/dashboard/layout/Navbar.tsx
we need to break down this file and distribute its components in smaller UI and layout

2024-05-10 19:24 UTC, Buzxxx commented on src/components/dashboard/layout/SideMenu.tsx
we need to breakdown this file

2024-05-11 09:34 UTC, grvx-github commented on package-lock.json
The collections at heroicons are limited.  An alternative could be downloading and using icons individually rather than installing a package.

2024-05-11 16:21 UTC, closed without merging